// Bluedge

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges.Messenger;

[GenerateTypedNameReferences]
public sealed partial class MessengerUiChatItem : BoxContainer
{
    public MessengerUiChatItem(string chatName, string lastMessage,
        Action<BaseButton.ButtonEventArgs>? onPressedOpenChatHistory, bool isNewMessage)
    {
        RobustXamlLoader.Load(this);
        ChatName.Text = chatName;

        LastMessage.FontColorOverride = isNewMessage ? Color.DarkGoldenrod : Color.DarkGray;
        LastMessage.Text = Truncate(lastMessage, 40);

        OpenChatHistoryButton.OnPressed += onPressedOpenChatHistory;
    }

    public MessengerUiChatItem()
    {
        RobustXamlLoader.Load(this);
    }

    private static string? Truncate(string? value, int maxLength, string truncationSuffix = "…")
    {
        return value?.Length > maxLength ? value[..maxLength] + truncationSuffix : value;
    }
}
