- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Aspid
  - Bluedge_saltern
  - Bluedge_Marathon
  - Bluedge_Claster
#  - Bagel
  - Barratry
  - CorvaxDelta
  - Box
#  - Cluster
#  - Core
#  - Fland
#  - Kettle
#  - Marathon
#  - Meta
#  - Omega
  - Origin
  # - Saltern
  # - Packed
