- type: loadout
  id: LoadoutCommandHOSNeckMantle
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - HeadOfSecurity
  items:
    - ClothingNeckMantleHOS

- type: loadout
  id: LoadoutCommandHOSNeckCloak
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - HeadOfSecurity
  items:
    - ClothingNeckCloakHos

- type: loadout
  id: LoadoutCommandHOSJumpsuitAlt
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - HeadOfSecurity
  items:
    - ClothingUniformJumpsuitHoSAlt

- type: loadout
  id: LoadoutCommandHOSJumpsuitBlue
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - HeadOfSecurity
  items:
    - ClothingUniformJumpsuitHoSBlue

- type: loadout
  id: LoadoutCommandHOSJumpsuitGrey
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - HeadOfSecurity
  items:
    - ClothingUniformJumpsuitHoSGrey

- type: loadout
  id: LoadoutCommandHOSJumpsuitParade
  category: Jobs
  cost: 3
  exclusive: true
  jobWhitelist:
    - HeadOfSecurity
  items:
    - ClothingUniformJumpsuitHoSParadeMale

- type: loadout
  id: LoadoutCommandHOSJumpsuitFormal
  category: Jobs
  cost: 3
  exclusive: true
  jobWhitelist:
    - HeadOfSecurity
  items:
    - ClothingUniformJumpsuitHosFormal

- type: loadout
  id: LoadoutCommandHOSJumpskirtAlt
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - HeadOfSecurity
  items:
    - ClothingUniformJumpskirtHoSAlt

- type: loadout
  id: LoadoutCommandHOSJumpskirtParade
  category: Jobs
  cost: 3
  exclusive: true
  jobWhitelist:
    - HeadOfSecurity
  items:
    - ClothingUniformJumpskirtHoSParadeMale

- type: loadout
  id: LoadoutCommandHOSJumpskirtFormal
  category: Jobs
  cost: 3
  exclusive: true
  jobWhitelist:
    - HeadOfSecurity
  items:
    - ClothingUniformJumpskirtHosFormal

- type: loadout
  id: LoadoutCommandHOSOuterWinter
  category: Jobs
  cost: 2
  jobWhitelist:
    - HeadOfSecurity
  items:
    - ClothingOuterWinterHoS

- type: loadout
  id: LoadoutCommandHOSOuterTrench
  category: Jobs
  cost: 2
  jobWhitelist:
    - HeadOfSecurity
  items:
    - ClothingOuterCoatHoSTrench

- type: loadout
  id: LoadoutCommandHOSHatBeret
  category: Jobs
  cost: 1
  jobWhitelist:
    - HeadOfSecurity
  items:
    - ClothingHeadHatBeretHoS

- type: loadout
  id: LoadoutCommandHOSHatHoshat
  category: Jobs
  cost: 1
  jobWhitelist:
    - HeadOfSecurity
  items:
    - ClothingHeadHatHoshat