// Bluedge
using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.CriminalRecords.UI;

[GenerateTypedNameReferences]
public sealed partial class RecordListGroupBasic : RecordListGroup
{
    public RecordListGroupBasic() : base()
    {
        RobustXamlLoader.Load(this);
        RecordContainer = this;
    }

    public override void SetGroupName(string name)
    {
        base.SetGroupName(name);
        GroupNameLabel.SetMarkup($"[color={Color.ToHexNoAlpha()}]{GroupName}[/color]");
    }
}
